### ISSUE TITLE
[UPSTREAM] Upstream misskey support patch

### ISSUE THREAD

**Issue by perillamint** [Interstellar-Relay-Community/aode-relay#7]
Misskey support would be helpful when upstreamed to asonix original repository.

## Tasks
* [ ] Refactor the patch for the upstreaming
* [ ] Submit the patch
* [ ] Rebase our dev & next against it
